config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'documents#index'

  resources :documents
  get '/documents/:id/json/body', to: 'documents#json_document'
  get '/documents/:id/json/title', to: 'documents#json_title'
  get '/documents/:id/json/size', to: 'documents#json_size'
  
  resources :users do
    resource :user_settings, only: [:edit, :update]
  end
  patch '/users/:user_id/user_settings/edit', to: 'user_settings#update'
  get '/users/:user_id/user_settings/json', to: 'user_settings#user_settings_json'
  get '/user_settings/json', to: 'user_settings#user_settings_json'

  get  '/signup',    to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :size, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 300 }

  before_save do 
    self.body ||= '{}'
    self.size ||= 100
  end
  serialize :body, JSON
end

app/models/setting.rb
class Setting < ApplicationRecord
  validates :color, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 360 }
  validates :theme, presence: true, inclusion: { in: %w(light dark system) }
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save :assign_default_setting, if: -> { self.setting_id.blank? }

  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  has_many :documents
  has_one :setting

  private

  def assign_default_setting
    default_setting = Setting.find_by(default: true)
    if default_setting
      self.setting ||= Setting.create(
        color: default_setting.color,
        theme: default_setting.theme,
        sidebar: default_setting.sidebar,
        default: false
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include UserSettingsHelper
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :json_document, :json_title, :json_size, :update]
  
  def index
    return redirect_to login_path unless logged_in? 
    @documents = current_user.documents
    if (logged_in?)
      if (@documents.length == 0)
        flash[:info] = "Create your first document!" if @documents.length == 0
        redirect_to new_document_path
      end
    end
  end
  
  def json_title
    render json: @document.title.to_json
  end

  def json_size
    render json: @document.size.to_json
  end
  
  def json_document
    render json: JSON.parse(@document.body)
  end

  def new
    @document = Document.new(title: 'Document')
  end

  def create
    @document = current_user.documents.build({ title: document_params[:title], size: 100})
    if @document.save
      flash[:success] = 'Document was successfully created.'
      redirect_to @document
    else
      render :new
    end
  end

  def update
    if @document.update(document_params)
      render json: @document, status: :ok
    else
      render json: { error: 'Failed to update document' }, status: :unprocessable_entity
    end
  end
  
  private
  
  def set_document
    @document = Document.find(params[:id])
  end
  
  def document_params
    params.require(:document).permit(:title, :body, :size)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_url, flash: { info: 'Already logged in' } if logged_in?
  end

  def create
    return if logged_in?
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_to documents_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    return unless logged_in?
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/user_settings_controller.rb
class UserSettingsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  
  def edit
    @user = User.find(params[:user_id])
    @user_settings = @user.setting
  end

  def user_settings_json
    if params[:user_id] 
      @user = User.find(params[:user_id])
    else 
      @user = current_user
    end
    @user_settings = @user.setting
    render json: @user_settings
  end

  def update
    @user = User.find(params[:user_id])
    @user_settings = @user.setting

    if @user_settings.update(user_settings_params)
      flash[:success] = "Settings updated."
      render 'edit'
    else
      render 'edit'
    end
  end

  private

  def user_settings_params
    params.require(:setting).permit(:color, :theme, :sidebar)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
  end

  def new
    return redirect_to root_path if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Success! Welcome #{@user.name}!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def log_out
    reset_session
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def authenticate_user!
    @user = User.find_by(id: params[:id])
    if (@user != nil) & (current_user != @user)
      flash[:danger] = "Not authorized."
      redirect_back(fallback_location: root_url) 
    end
  end
end

app/helpers/user_settings_helper.rb
module UserSettingsHelper
  def color
    if current_user
      current_user.setting.color
    end
  end
  
  def sidebar
    if current_user
      current_user.setting.sidebar
    end
  end

  def theme
    if current_user
      current_user.setting.theme
    end
  end

  def setting_to_json
    { color: color, sidebar: sidebar, theme: theme}.to_json.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/index.html.erb
<div class='content'>
  <div class='search-toolbar'>
    <div class="tooltip">
      <%= link_to "add", new_document_path, class:'material-symbols-sharp' %>
      <div class="tooltip-text">Add</div>
    </div>
    <div class="tooltip">
      <%= link_to "more_horiz", root_path, class:'material-symbols-sharp' %>
      <div class="tooltip-text">More</div>
    </div>
    <div class="flex-grow"></div>
    <div class='material-symbols-sharp search-icon'>search</div> 
    <%= form_with local: true do |f| %>
      <%= f.text_field :search, class: 'form-control', placeholder: 'Search...' %>
    <% end %>
  </div>
  <div class='document-list'>
    <% @documents.each do |document| %>
      <div class='document-item'>
        <div class='material-symbols-sharp'>note</div>
        <%= link_to document.title, document %>
      </div>
    <% end %>
  </div>
</div>

app/views/documents/new.html.erb
<%= render 'shared/error_messages', object: @document %>
<div class="content">
  <div class="h3">New Document</div>
  <%= form_with model: @document, class: 'form', local: true do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      
      <%= f.submit "Submit", class: "submit-button" %>
  <% end %>
</div>

app/views/documents/show.html.erb
<div id='DocumentEditor' data-id="<%= @document.id %>">Loading...</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compose</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  </head>
  <body>
    <% if sidebar %>
      <div class="sidebar-container">
        <%= render 'shared/sidebar' %>
        <%= yield %>
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      <div>
    <% else %>
      <%= render 'shared/header' %>
      <%= yield %>
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
    <% end %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object %>
  <% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div>
    <%= link_to "Compose", root_url, class: 'h2' %>
    <div class='flex-grow'></div>
    <nav>
      <% if logged_in? %>
        <div class="tooltip">
          <%= link_to "settings", edit_user_user_settings_path(current_user), class: 'material-symbols-sharp' %>
          <div class="tooltip-text">Settings</div>
        </div>
        <div class="tooltip">
          <%= link_to "account_circle", current_user, class: 'material-symbols-sharp' %>
          <div class="tooltip-text">Profile</div>
        </div>
        <div class="tooltip">
          <%= link_to "logout", logout_path, class: 'material-symbols-sharp', method: :delete %>
          <div class="tooltip-text">Logout</div>
        </div>
      <% else %>
        <div class="tooltip">
          <%= link_to "login", login_path, class: 'material-symbols-sharp'%>
          <div class="tooltip-text">Login</div>
        </div>
      <% end %>
    </nav>
  </div>
</header>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
  <%= link_to "Compose", root_url, class: 'h2' %>
  <hr>
  <% if logged_in? %>
    <%= button_to(documents_url, method: :get, class: 'button_to') do %>
      <div class="sidebar-item">
        <div class='material-symbols-sharp'>note</div>
        <div class="sidebar-item-text">Documents</div>
      </div>
    <% end %>
    <div class="flex-grow"></div>
    <%= button_to(edit_user_user_settings_path(current_user), method: :get, class: 'button_to') do %>
      <div class="sidebar-item">
        <div class='material-symbols-sharp'>settings</div>
        <div class="sidebar-item-text">Settings</div>
      </div>
    <% end %>
    <%= button_to(current_user, method: :get, class: 'button_to') do %>
      <div class="sidebar-item">
        <div class='material-symbols-sharp'>account_circle</div>
        <div class="sidebar-item-text">Profile</div>
      </div>
    <% end %>
    <%= button_to(logout_path, method: :delete, class: 'button_to') do %>
      <div class="sidebar-item">
        <div class='material-symbols-sharp'>logout</div>
        <div class="sidebar-item-text">Logout</div>
      </div>
    <% end %>
  <% else %>
    <div class="sidebar-item">
      <%= link_to "login", login_path, class: 'material-symbols-sharp'%>
      <div class="sidebar-item-text">Login</div>
    </div>
  <% end %>
</div>

app/views/user_settings/edit.html.erb
<div class="content">
  <div class="h3">Settings</div>
  <div id="Settings" data-id="<%= @user.id %>"/>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true, class:'form') do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit "Submit", class: "submit-button" %>
<% end %>

app/views/users/edit.html.erb
<div class="content">
  <div class="h3">Update User</div>
  <%= render 'form' %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class='content'>
  <div class='h3'>Sign up</div>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class='content'>
  <div class="h3">Account</div>
  <form class="form">
    <label>Name</label>
    <%= @user.name %>
    <label>Email</label>
    <%= @user.email %>
  </form>
  <%= link_to 'Edit Account', edit_user_path %>
</div>